"""add_user_profile_fields

Revision ID: placeholder_user_profile_rev_id
Revises: placeholder_shipment_revision_id
Create Date: YYYY-MM-DD HH:MM:SS.MS+2

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'placeholder_user_profile_rev_id'
down_revision: Union[str, None] = 'placeholder_shipment_revision_id' # Points to the shipment table migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('default_address_json', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('email_notifications_enabled', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.add_column('users', sa.Column('sms_notifications_enabled', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.add_column('users', sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('default_service_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_pickup_window_start', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_pickup_window_end', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_pickup_window_end')
    op.drop_column('users', 'preferred_pickup_window_start')
    op.drop_column('users', 'default_service_level')
    op.drop_column('users', 'terms_accepted_at')
    op.drop_column('users', 'sms_notifications_enabled')
    op.drop_column('users', 'email_notifications_enabled')
    op.drop_column('users', 'default_address_json')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
