"""create_shipment_table

Revision ID: placeholder_shipment_revision_id
Revises: placeholder_revision_id 
Create Date: YYYY-MM-DD HH:MM:SS.MS+1

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'placeholder_shipment_revision_id'
down_revision: Union[str, None] = 'placeholder_revision_id' # Points to the user table migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tracking_number', sa.String(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pickup_address', sa.JSON(), nullable=False),
    sa.Column('delivery_address', sa.JSON(), nullable=False),
    sa.Column('pickup_datetime_window_start', sa.DateTime(), nullable=True),
    sa.Column('pickup_datetime_window_end', sa.DateTime(), nullable=True),
    sa.Column('delivery_datetime_window_start', sa.DateTime(), nullable=True),
    sa.Column('delivery_datetime_window_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('service_level', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('package_details', sa.String(), nullable=True),
    sa.Column('special_instructions', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=True)
    op.create_index(op.f('ix_shipments_user_id'), 'shipments', ['user_id'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_index(op.f('ix_shipments_service_level'), 'shipments', ['service_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_service_level'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_user_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
