import pytest
import uuid
from httpx import AsyncClient
from fastapi import status

from app.schemas.user import UserRead, UserCreate
from app.schemas.token import Token

# Helper to generate unique email
def unique_email() -> str:
    return f"testuser_{uuid.uuid4().hex[:6]}@example.com"

@pytest.mark.asyncio
async def test_user_registration(client: AsyncClient, db_session): # Add db_session for potential cleanup or setup if needed
    email = unique_email()
    password = "SecurePassword123"
    
    # 1. Register a new user
    response = await client.post(
        "/api/v1/auth/register",
        json={"email": email, "password": password},
    )
    assert response.status_code == status.HTTP_200_OK # Based on current endpoint returning 200
    user_data = response.json()
    assert user_data["email"] == email
    assert "id" in user_data
    assert "hashed_password" not in user_data # Ensure password is not returned

    # 2. Attempt to register the same user again
    response_conflict = await client.post(
        "/api/v1/auth/register",
        json={"email": email, "password": password},
    )
    assert response_conflict.status_code == status.HTTP_400_BAD_REQUEST
    assert "Email already registered" in response_conflict.json()["detail"]

@pytest.mark.asyncio
async def test_user_login(client: AsyncClient, db_session):
    email = unique_email()
    password = "LoginPassword456"

    # 1. Register a user first (ensure user exists for login test)
    await client.post("/api/v1/auth/register", json={"email": email, "password": password})

    # 2. Log in with correct credentials
    login_response = await client.post(
        "/api/v1/auth/login",
        data={"username": email, "password": password}, # OAuth2PasswordRequestForm uses form data
    )
    assert login_response.status_code == status.HTTP_200_OK
    token_data = login_response.json()
    assert "access_token" in token_data
    assert "refresh_token" in token_data
    assert token_data["token_type"] == "bearer"

    # 3. Attempt to log in with incorrect password
    login_fail_password_response = await client.post(
        "/api/v1/auth/login",
        data={"username": email, "password": "WrongPassword"},
    )
    assert login_fail_password_response.status_code == status.HTTP_401_UNAUTHORIZED
    assert "Incorrect email or password" in login_fail_password_response.json()["detail"]

    # 4. Attempt to log in with a non-existent user
    non_existent_email = unique_email()
    login_fail_user_response = await client.post(
        "/api/v1/auth/login",
        data={"username": non_existent_email, "password": password},
    )
    assert login_fail_user_response.status_code == status.HTTP_401_UNAUTHORIZED # Or 404 depending on strict error handling
    assert "Incorrect email or password" in login_fail_user_response.json()["detail"]


# Password recovery flow tests are more complex due to token generation and verification.
# These tests will assume the token mechanism works as unit-tested in test_security.py,
# and focus on the endpoint logic.
# Actual token verification (e.g. if it's emailed) is out of scope for this integration test.

@pytest.mark.asyncio
async def test_password_recovery_request(client: AsyncClient, db_session):
    email = unique_email()
    password = "RecoveryPassword789"

    # 1. Register a user
    await client.post("/api/v1/auth/register", json={"email": email, "password": password})

    # 2. Request password recovery for an existing user
    response = await client.post(f"/api/v1/auth/password-recovery/{email}")
    assert response.status_code == status.HTTP_200_OK
    assert "Password recovery email sent" in response.json()["msg"] # Or similar message

    # 3. Request password recovery for a non-existent user
    non_existent_email = unique_email()
    response_non_existent = await client.post(f"/api/v1/auth/password-recovery/{non_existent_email}")
    assert response_non_existent.status_code == status.HTTP_404_NOT_FOUND


# test_reset_password needs a valid token. This is hard to get directly in an integration test
# without mocking or accessing logs/emails.
# For now, this test will be more of a placeholder or will test failure modes.
# A full flow test would require more setup (e.g., a fixture to get a valid reset token).

@pytest.mark.asyncio
async def test_reset_password_invalid_token(client: AsyncClient, db_session):
    response = await client.post(
        "/api/v1/auth/reset-password/",
        json={"token": "invalid.fake.token", "new_password": "NewPassword123!"}
    )
    assert response.status_code == status.HTTP_400_BAD_REQUEST
    assert "Invalid or expired password reset token" in response.json()["detail"]

# To test the valid reset password flow:
# 1. Need a way to get the token generated by /password-recovery/{email}.
#    - Could capture from console print (if that's how it's "sent" in test mode).
#    - Could mock the create_password_reset_token to return a known value, or store it.
# For now, a full valid flow test for reset_password is omitted due to this complexity.
# The unit tests for token generation/verification in test_security.py cover the token logic itself.
```
